flask:
    PROPAGATE_EXCEPTIONS: True
    DEBUG: True
    LOG_LEVEL: debug

database:
    DBNAME: pyris
    USER: postgres
    PASSWORD: myPassword
    HOST: localhost
    PORT: 5432

uwsgi:
    master: true
    pythonpath: ~/src/pyris
    socket: localhost:8855
    module: pyris.api.wsgi:app
    processes: 1
    enable-threads: true
    protocol: uwsgi
    need-app: true
    catch: exceptions=true
    touch: reload=~/pyris-app.reload
